services:
  anaconda:
    build:
      context: ./
      dockerfile: Dockerfile
    command: >
      /bin/bash -c "jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser --allow-root"
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/opt/notebooks  # Persist notebooks outside the container
    tty: true  # Equivalent to -t (allocate a pseudo-TTY)
    stdin_open: true  # Equivalent to -i (keep STDIN open)
